---
- name: Add users using variables to a Rocky host
  hosts: LL-rocky9-01
  gather_facts: false
  # vars_files:
  #   - files/users.yml
  vars:
    # new_user: test1
  tasks:
    - name: Add users to the Rocky host
      ansible.builtin.user:
        name: "{{ new_user }}"
        state: present
      vars:
        new_user: test1
