---
- name: Add nginx webserver to a Rocky host
  hosts: LL-rocky9-01
  gather_facts: false
  vars:

  tasks:
    - name: Block for rocky hosts
      when: "'rocky' in ansible_facts['distribution']"
      block:
        - name: Install nginx webserver
          ansible.builtin.dnf:
            name: nginx
            state: present
        - name: Start and enable nginx service
          ansible.builtin.systemd:
            name: nginx
            enabled: yes
            state: started

    - name: Block for ubuntu hosts
      when: "'ubuntu' in ansible_facts['distribution']"
      block:
        - name: Install nginx webserver
          ansible.builtin.apt:
            name: nginx
            state: present
        - name: Start and enable nginx service
          ansible.builtin.systemd:
            name: nginx
            enabled: yes
            state: started