---
- name: Add/configure nginx webserver on a Rocky host
  hosts: LL-rocky9-01
  gather_facts: false
  vars:
    owner_name: Greg Sowell
    
  tasks:
    - name: Block for rocky hosts
      when: "'rocky' in ansible_facts['distribution']"
      block:
        - name: Install nginx webserver
          ansible.builtin.dnf:
            name: nginx
            state: latest
          notify: Restart nginx

        - name: Start and enable nginx service
          ansible.builtin.systemd:
            name: nginx
            enabled: yes
            state: started
      tags: 
        - install

    - name: Block for ubuntu hosts
      when: "'ubuntu' in ansible_facts['distribution']"
      block:
        - name: Install nginx webserver
          ansible.builtin.apt:
            name: nginx
            state: latest
          notify: Restart nginx
          
        - name: Start and enable nginx service
          ansible.builtin.systemd:
            name: nginx
            enabled: yes
            state: started
      tags: 
        - install

    - name: Create /home/webserver directory
      ansible.builtin.file:
        path: /home/webserver
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'
      tags: 
        - configure

    - name: Add index.html to webserver directory
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /home/webserver/index.html
        owner: nginx
        group: nginx
        mode: '0644'
      tags: 
        - configure

    - name: Add nginx config based on template
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: nginx
        group: nginx
        mode: '0644'
      notify: Restart nginx
      tags: 
        - configure

  handlers:
    - name: Restart nginx service when nginx config changes
      when: nginx_config.changed
      ansible.builtin.systemd:
        name: nginx
        state: restarted
      