---
- name: Add/configure nginx webserver on a Rocky host
  hosts: LL-rocky9-01
  # gather_facts: false
  become: true
  vars:
    owner_name: Greg Sowell
    web_path: /home/webserver
    
  tasks:
    - name: Block for rocky hosts
      when: "'Rocky' in ansible_facts['distribution']"
      block:
        - name: Install nginx webserver
          ansible.builtin.dnf:
            name: nginx
            state: latest
          notify: Restart nginx

        - name: Start and enable nginx service
          ansible.builtin.systemd:
            name: nginx
            enabled: yes
            state: started

    - name: Block for ubuntu hosts
      when: "'Ubuntu' in ansible_facts['distribution']"
      block:
        - name: Install nginx webserver
          ansible.builtin.apt:
            name: nginx
            state: latest
          notify: Restart nginx
          
        - name: Start and enable nginx service
          ansible.builtin.systemd:
            name: nginx
            enabled: yes
            state: started

    - name: Create /home/webserver directory
      ansible.builtin.file:
        path: /home/webserver
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'

    - name: Add index.html to webserver directory
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /home/webserver/index.html
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Add nginx config based on template
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: nginx
        group: nginx
        mode: '0644'
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
      