---
- name: Add users using loops, conditionals, and variables to a Rocky host
  hosts: LL-rocky9-01
  gather_facts: false
  vars:
    ignore_users:
      - root
      - test1
      
    new_user:
      - test1
      - test2
      - test3

  tasks:
    - name: Add users to the Rocky host
      # when: item not in ignore_users and ignore_users is defined
      when: item not in ignore_users | default(omit)
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop: "{{ new_user }}"
      become: true
