---
- name: Check for a user on a Rocky host
  hosts: LL-rocky9-01
  gather_facts: false
  vars:

  tasks:
    - name: Check for a user with the id command
      ansible.builtin.command: id greg
      register: user_id
      changed_when: false
      failed_when: false

    - name: Print out info on the user
      ansible.builtin.debug:
        msg: "{{ user_id.stdout_lines | default('User not found') }}"
      # when: check_user | intersect(user_id.stdout_lines) | length > 0

    - name: Check for a user with the id command
      ansible.builtin.command: id test1
      register: user_id
      changed_when: false
      failed_when: false

    - name: Print out info on the user
      ansible.builtin.debug:
        msg: "{{ user_id.stdout_lines | default('User not found') }}"
      # when: check_user | intersect(user_id.stdout_lines) | length > 0