---
- name: A simple playbook to add users to a Rocky host
  hosts: LL-rocky9-01
  gather_facts: false
  # vars_files:
  #   - files/users.yml
  vars:

  tasks:
    - name: Include add_users role
      ansible.builtin.include_role:
        name: add_users